export default function Head() {
  return (
    <>
      <title>AVSJOBS | Projetos sob medida</title>
      <meta charSet="utf-8" />
      <meta content="IE=edge" httpEquiv="X-UA-Compatible" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/favicon.ico" />
      <meta name="description" content="Criamos soluções digitais sob medida, unindo aplicações escaláveis e design de excelência. Transformamos ideias em presença digital única." />
    </>
  );
}
